## Creating arrays

In [1]:
import numpy as np

In [2]:
a_list = [1, 2, 3]

In [3]:
array = np.array(a_list)

In [4]:
array

array([1, 2, 3])

In [5]:
a_listt = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
array2 = np.array(a_listt)

In [7]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr = np.ones(2)

In [10]:
arr

array([1., 1.])

In [11]:
arr2 = np.ones((2, 2))

In [12]:
arr2

array([[1., 1.],
       [1., 1.]])

In [17]:
arr3 = np.zeros((2, 2))

In [18]:
arr3

array([[0., 0.],
       [0., 0.]])

In [19]:
np.random.rand(2, 2)

array([[0.28516651, 0.42797224],
       [0.75508464, 0.53980583]])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.randint(20) # random integer. Argument is the stop value

5

In [25]:
np.random.randn(4, 4)

array([[-1.1223747 ,  0.58523964,  0.27700452,  0.59259798],
       [-1.76769579, -1.13842708,  0.94056098,  0.04781899],
       [-0.21276107,  1.60935456,  0.79129935,  0.12752701],
       [-1.51493874, -0.69409383,  0.99596207,  1.78696083]])

In [28]:
np.linspace(2, 100)

array([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
        24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,
        46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,
        68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,
        90.,  92.,  94.,  96.,  98., 100.])

## Numpy Attributes

In [29]:
arr4 = np.random.randint(0, 100, 16)

In [30]:
arr4

array([16, 24, 96, 60,  1, 74, 96, 86, 84,  1, 45,  4, 83, 82, 97, 36])

In [31]:
arr4.shape

(16,)

In [32]:
arr4.ndim

1

In [33]:
arr4.reshape(4, 4)

array([[16, 24, 96, 60],
       [ 1, 74, 96, 86],
       [84,  1, 45,  4],
       [83, 82, 97, 36]])

In [34]:
arr5 = arr4.reshape(4, 4)

In [35]:
arr5.shape

(4, 4)

In [36]:
arr4.dtype

dtype('int32')

## Indexing and Slicing

In [37]:
arr6 = np.arange(1, 10)

In [38]:
arr6

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr6[4]

5

In [40]:
arr6[2:5]

array([3, 4, 5])

In [41]:
arr7 = arr6.reshape(3, 3)

In [42]:
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr7[0, 2]

3

In [44]:
arr7[0]

array([1, 2, 3])

In [45]:
arr7[0, 1:]

array([2, 3])

In [46]:
arr7[:1, 1:]

array([[2, 3]])

In [47]:
arr7[1:, 1:]

array([[5, 6],
       [8, 9]])

## Numpy Array Operations

In [48]:
arr8 = np.array([2, 4])

In [49]:
arr9 = np.array([1, 2])

In [50]:
arr8

array([2, 4])

In [51]:
arr9

array([1, 2])

In [52]:
arr8 + arr9

array([3, 6])

In [53]:
arr8 - arr9

array([1, 2])

In [54]:
arr8 * arr9

array([2, 8])

In [55]:
arr8 / arr9

array([2., 2.])

In [56]:
arr8 * 2

array([4, 8])

In [57]:
arr10 = np.array([[1, 2], [3, 4], [4, 5]])

In [58]:
arr10

array([[1, 2],
       [3, 4],
       [4, 5]])

In [59]:
arr10 + arr8

array([[3, 6],
       [5, 8],
       [6, 9]])

In [60]:
arr10.max()

5

In [61]:
arr10.min()

1

In [62]:
arr10.sum()

19

In [63]:
arr10.max(axis=0)

array([4, 5])

In [64]:
arr10.max(axis=1)

array([2, 4, 5])

## Practical Example

In [65]:
predictions = np.array([2, 5, 6])
labels = np.array([1, 5, 8])

In [66]:
mse = (1/3) * np.sum(np.square(predictions - labels))

In [67]:
mse

1.6666666666666665